### ISSUE TITLE
v2.0.2 not on pub.dev

### ISSUE THREAD

**Issue by franzlst** [ryanhz/fluent-dart#4]
Hi,

you have released v2.0.2 on GitHub, which adds compatibility with intl 0.18. Somehow, the version is not available on pub.dev. Could you please check why and release it on pub.dev? Would be very helpful for us!

**Comment by mariahaubner** [comment]
Friendly bump @ryanhz

**Comment by ryanhz** [comment]
Ah, sorry, i didn't get notified via email. Will do it now

**Comment by mariahaubner** [comment]
No worries ;) 

And I don't want to be a pita, but Intl by now has moved to 0.19.0 https://github.com/dart-lang/i18n/tree/main/pkgs/intl

It is a shame, that the only dependency in this project always necessitates a new release even though nothing in the actual code changes

**Comment by ryanhz** [comment]
You can always use override to pin `Intl` package, which is depended by so many packages.

2.0.3 is live with `intl` 0.19.0.  
2.0.2 was half way released but interrupted and forgotten.
