### ISSUE TITLE
Variable substitution in terms does not work

### ISSUE THREAD

**Issue by exomo** [ryanhz/fluent-dart#5]
In the following example from the example file, the variable in the term should be evaluated:

```
-brand-name1 =
    { $case ->
       *[nominative] Firefox
        [locative] Firefoxa
    }

# "About Firefox."
about1 = Informacje o { -brand-name1(case: "locative") }.
```

Expected result when evaulating "about1": Informacje o Firefoxa
Actual result: Informacje o Firefox

**Comment by ryanhz** [comment]
Fixed in #6
